# Generated by Django 2.2.5 on 2019-10-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battle',
            options={'verbose_name_plural': 'Battle'},
        ),
        migrations.AlterModelOptions(
            name='kingdom',
            options={'verbose_name_plural': 'Kingdom'},
        ),
    ]
