# Generated by Django 2.2.5 on 2019-10-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartoon_network', models.CharField(max_length=30)),
                ('pogo', models.CharField(max_length=30)),
                ('disney', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_sports', models.CharField(max_length=30)),
                ('discovery', models.CharField(max_length=30)),
                ('national_geography', models.CharField(max_length=30)),
            ],
        ),
    ]
